import RegisterAmount from '~/app/dashboard/my-expenses/register-amount';

export default function DashboardRegisterPersonalExpense() {
  return <RegisterAmount target="expenses" descriptions={descriptions} title="Register expense" />;
}

const descriptions = [
  'Actors',
  'Adventures',
  'Appliances',
  'Apps',
  'Cafes',
  'Car',
  'Concerts',
  'Conferences',
  'Costumes',
  'Electronics',
  'Exhibitions',
  'Festivals',
  'Fitness',
  'Food',
  'Games',
  'Gaming',
  'Gas',
  'Groceries',
  'Holidays',
  'Insurances',
  'Internet',
  'Movies',
  'Museums',
  'Music',
  'Netflix',
  'Parties',
  'Phone',
  'Rent',
  'Restaurants',
  'Savings',
  'Seminars',
  'Shows',
  'Snacks',
  'Sports',
  'Sweets',
  'Taxes',
  'Training',
  'Trips',
  'University',
  'Vacations',
  'Water',
  'Webinars',
  'Workshops',
];
