#!/usr/bin/env bash

TICKET=$(git branch --show-current | sed 's/^\(.*\)--\(.*\)$/\1/' | tr '[:lower:]' '[:upper:]')
DESC=$(git branch --show-current | sed 's/^.*--\(.*\)$/\1/;s/-/ /')

if [[ $(gh pr list --json 'headRefName,baseRefName' | jq "[ .[] | select(.baseRefName == \"dev\" and .headRefName == \"$(git branch --show-current)\") ] | length") -gt 0 ]]; then
  echo "WARN: PR already exists, skipping."
  exit 0
fi

gh pr create -B dev -H $(git branch --show-current) -t "$TICKET - $DESC" -b "$DESC"
