#!/usr/bin/env bash

if [[ $(gh pr list --json 'headRefName,baseRefName' | jq "[ .[] | select(.headRefName == \"dev\" and .baseRefName == \"main\") ] | length") -gt 0 ]]; then
  exit 0
fi

gh pr create -B main -H dev -t "Prod release" -b "This PR has been created automatically by a GitHub Action."
