#!/usr/bin/env bash

TICKET=$(git branch --show-current | sed 's/^\(.*\)--\(.*\)$/\1/' | tr '[:lower:]' '[:upper:]')
DESC=$(git branch --show-current | sed 's/^.*--\(.*\)$/\1/;s/-/ /')

if [[ $(gh pr list --json 'headRefName,baseRefName' | jq "[ .[] | select(.headRefName == \"dev\" and .baseRefName == \"main\") ] | length") -gt 0 ]]; then
  exit 0
fi

gh pr create -B main -H dev -t "Prod release" -b "This PR has been created automatically by a GitHub Action."
