name: create pull request to main

on:
  push:
    branches:
      - dev

jobs:
  createDraftPR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute bash script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./scripts/create-pr-to-main
          ./scripts/create-pr-to-main
